version: '2'
services:
 site1:
  build:
   context: ./site1
   dockerfile: Dockerfile
  ports:
  - "11111:80"
 site2:
  image: nginx:latest
  ports:
  - "22222:80"
  volumes:
  - ./site2/html:/var/www/html
  - ./site2/html:/usr/share/nginx/html/
  - ./site2/default.conf:/etc/nginx/conf.d/default.conf
  depends_on:
  - php1
  - php2
  - php3
 php1:
  image: php:7-fpm
  volumes:
  - ./site2/html:/var/www/html
 php2:
  image: php:7-fpm
  volumes:
  - ./site2/html:/var/www/html
 php3:
  image: php:7-fpm
  volumes:
  - ./site2/html:/var/www/html
